apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: board-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: board-api
    spec:
      containers:
        - name: board-api
          image: sktellecom/ms-test:board-api
          ports:
            - containerPort: 8090
          imagePullPolicy: Always
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: ms-secret